import React, { useEffect, useState } from 'react';
import { Text, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { Screen } from '../components/Screen';
import { colors, radius } from '../theme/colors';
import { type } from '../theme/typography';
import { getBlocks, Block } from '../services/chain';
import { useApp } from '../store/app';
export function Network(){const {rpcUrl,status}=useApp();const[blocks,setBlocks]=useState<Block[]>([]);useEffect(()=>{getBlocks(rpcUrl,12).then(setBlocks).catch(()=>setBlocks([]))},[rpcUrl,status?.height]);return <Screen><Animated.View entering={FadeInDown.duration(400)}><Text style={{...type.title,color:colors.text}}>RainX Network</Text><Text style={{...type.bodySmall,color:colors.muted,marginTop:5}}>Independent chain • {status?.chainId||'rainx-mainnet-1'}</Text><View style={{flexDirection:'row',gap:10,marginTop:20}}><Metric title="Height" value={String(status?.height??'—')}/><Metric title="Mempool" value={String(status?.mempool??'—')}/><Metric title="PoW" value="18 bits"/></View><Text style={{...type.headline,color:colors.text,marginTop:28,marginBottom:12}}>Latest blocks</Text><View style={{backgroundColor:colors.card,borderWidth:1,borderColor:colors.hairline,borderRadius:radius.lg,paddingHorizontal:16}}>{blocks.slice().reverse().map((b)=><View key={b.header.height} style={{paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.hairline,flexDirection:'row',alignItems:'center'}}><View style={{width:42,height:42,borderRadius:13,backgroundColor:colors.goldSoft,alignItems:'center',justifyContent:'center'}}><Text style={{fontWeight:'900',color:colors.goldDark}}>#{b.header.height}</Text></View><View style={{flex:1,marginLeft:12}}><Text style={{...type.body,fontWeight:'700',color:colors.text}}>Block {b.header.height}</Text><Text style={{...type.caption,color:colors.muted,marginTop:3}}>{b.transactions.length} transaction{b.transactions.length===1?'':'s'} • {new Date(b.header.timestamp*1000).toLocaleTimeString()}</Text></View><Text style={{...type.caption,color:colors.muted,fontFamily:'monospace'}}>{b.header.prevHash.slice(0,6)}…</Text></View>)}</View></Animated.View></Screen>}
function Metric({title,value}:{title:string;value:string}){return <View style={{flex:1,backgroundColor:colors.card,borderWidth:1,borderColor:colors.hairline,borderRadius:radius.md,padding:14}}><Text style={{...type.caption,color:colors.muted}}>{title}</Text><Text style={{...type.headline,color:colors.text,marginTop:5}}>{value}</Text></View>}
