import React, { useState } from 'react';
import { Alert, Pressable, Text, TextInput, View } from 'react-native';
import Animated, { FadeInDown, FadeInUp } from 'react-native-reanimated';
import { colors, radius } from '../theme/colors';
import { type } from '../theme/typography';
import { RainXLogo } from '../components/RainXLogo';
import { Button } from '../components/Button';
import { createWallet, importWallet } from '../store/wallet';
import { useApp } from '../store/app';
import { Screen } from '../components/Screen';
import { SuccessLottie } from '../components/SuccessLottie';

export function Onboarding(){
  const [mode,setMode]=useState<'start'|'phrase'|'backup'>('start'); const [phrase,setPhrase]=useState(''); const [newPhrase,setNewPhrase]=useState(''); const [done,setDone]=useState(false); const {reloadWallet}=useApp();
  const restore=async()=>{try{await importWallet(phrase);await reloadWallet();}catch(e){Alert.alert('Could not restore wallet',e instanceof Error?e.message:'Invalid recovery phrase.')}};
  const create=async()=>{try{const result=await createWallet();setNewPhrase(result.mnemonic);setMode('backup');}catch(e){Alert.alert('Wallet creation failed',e instanceof Error?e.message:'Could not create wallet.')}};
  if(mode==='phrase') return <Screen><Animated.View entering={FadeInDown.duration(450)} style={{paddingTop:20}}><Pressable onPress={()=>setMode('start')} hitSlop={12}><Text style={{...type.bodySmall,color:colors.goldDark,fontWeight:'800'}}>‹ Back</Text></Pressable><Text style={{...type.title,color:colors.text,marginTop:24}}>Restore your wallet</Text><Text style={{...type.body,color:colors.muted,marginTop:8}}>Enter your recovery phrase. It never leaves this device.</Text><TextInput value={phrase} onChangeText={setPhrase} placeholder="word word word …" placeholderTextColor="#9B9B9F" multiline autoCapitalize="none" autoCorrect={false} style={{marginTop:20,minHeight:180,borderRadius:16,borderWidth:1,borderColor:colors.hairline,padding:16,fontSize:17,lineHeight:25,color:colors.text,textAlignVertical:'top',backgroundColor:colors.card}}/><View style={{height:16}}/><Button title="Restore wallet" disabled={!phrase.trim()} onPress={restore}/></Animated.View></Screen>;
  if(mode==='backup') {const words=newPhrase.split(' '); return <Screen><Animated.View entering={FadeInUp.duration(500)}><View style={{alignItems:'center'}}><SuccessLottie size={88}/></View><Text style={{...type.title,color:colors.text,textAlign:'center'}}>Back up your wallet</Text><Text style={{...type.bodySmall,color:colors.muted,textAlign:'center',marginTop:7}}>This 24-word phrase is the only recovery path for this wallet.</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:22}}>{words.map((w,i)=><View key={`${i}-${w}`} style={{paddingHorizontal:10,paddingVertical:8,borderRadius:radius.sm,borderWidth:1,borderColor:colors.hairline,backgroundColor:colors.card}}><Text style={{fontSize:14,color:colors.text,fontWeight:'600'}}><Text style={{color:colors.muted}}>{i+1} </Text>{w}</Text></View>)}</View><View style={{marginTop:18,padding:13,borderRadius:radius.md,backgroundColor:colors.dangerSoft}}><Text style={{...type.bodySmall,color:colors.danger,fontWeight:'700'}}>Never screenshot, message, or share these words.</Text></View><View style={{height:16}}/><Button title={done?'Enter RainX Wallet':'I wrote it down'} onPress={async()=>{if(!done){setDone(true);return;}await reloadWallet();}}/></Animated.View></Screen>}
  return <Screen><View style={{flex:1,justifyContent:'space-between',paddingTop:30,paddingBottom:10}}><Animated.View entering={FadeInDown.duration(550)}><RainXLogo size={62}/><Text style={{...type.hero,color:colors.text,marginTop:23}}>Native RXC.{"\n"}Built for RainX.</Text><Text style={{...type.body,color:colors.muted,marginTop:13,maxWidth:345}}>A self-custody wallet for the independent RainX Network — with local transaction signing and real chain data.</Text></Animated.View><Animated.View entering={FadeInUp.delay(130).duration(500)}><View style={{gap:12}}><Button title="Create a new wallet" onPress={create}/><Button title="I already have a wallet" variant="secondary" onPress={()=>setMode('phrase')}/><Text style={{...type.caption,color:colors.muted,textAlign:'center',marginTop:6}}>Your recovery phrase stays private.</Text></View></Animated.View></View></Screen>
}
