import React, { useMemo, useState } from 'react';
import { Alert, Text, TextInput, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useApp } from '../store/app';
import { getUtxos, parseRxc, formatRxcAtomic, submitTransaction } from '../services/chain';
import { walletKeys } from '../store/wallet';
import { buildTransfer, signTransaction, transactionId } from '../utils/transaction';
import { Screen } from '../components/Screen';
import { Button } from '../components/Button';
import { colors, radius } from '../theme/colors';
import { type } from '../theme/typography';
import { Icon } from '../components/Icons';
export function Send({navigation}:any){const{wallet,rpcUrl,balance,refresh}=useApp();const[to,setTo]=useState('');const[amount,setAmount]=useState('');const[memo,setMemo]=useState('');const[busy,setBusy]=useState(false);const parsed=useMemo(()=>{try{return parseRxc(amount)}catch{return null}},[amount]);
 const send=async()=>{if(!wallet||!parsed)return; if(to.trim()===wallet.address){Alert.alert('Invalid recipient','You cannot send to the same address.');return;}setBusy(true);try{const utxos=await getUtxos(rpcUrl,wallet.address);let total=0n;const selected:{txid:string;vout:number}[]=[];for(const u of utxos){selected.push({txid:u.txid,vout:u.vout});total+=BigInt(u.value);if(total>=parsed)break;}if(total<parsed)throw new Error('Insufficient confirmed RXC.');const outputs=[{value:Number(parsed),address:to.trim()}];const change=total-parsed;if(change>0n)outputs.push({value:Number(change),address:wallet.address});const {secretKey,publicKey}=walletKeys(wallet);const tx=buildTransfer(selected,outputs,memo.trim());const signed=signTransaction(tx,secretKey,publicKey);const result=await submitTransaction(rpcUrl,signed);await refresh();Alert.alert('Transaction submitted',result.txid,[{text:'Done',onPress:()=>navigation.goBack()}]);}catch(e){Alert.alert('Send failed',e instanceof Error?e.message:'Could not send RXC.')}finally{setBusy(false)}};
 return <Screen><Animated.View entering={FadeInDown.duration(400)}><Text style={{...type.title,color:colors.text}}>Send RXC</Text><Text style={{...type.bodySmall,color:colors.muted,marginTop:5}}>Signed locally on this device. Your private key never goes to the node.</Text><View style={{marginTop:24,gap:16}}><Field label="Recipient address"><TextInput value={to} onChangeText={setTo} autoCapitalize="none" autoCorrect={false} placeholder="RXC…" placeholderTextColor="#9B9B9F" style={styles.input}/></Field><Field label="Amount"><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00" placeholderTextColor="#9B9B9F" style={styles.amount}/><Text style={{...type.caption,color:colors.muted,marginTop:8}}>Available {formatRxcAtomic(balance)} RXC</Text></Field><Field label="Memo (optional)"><TextInput value={memo} onChangeText={setMemo} maxLength={80} placeholder="What's this for?" placeholderTextColor="#9B9B9F" style={styles.input}/></Field><View style={{padding:14,borderRadius:radius.md,backgroundColor:colors.goldSoft,flexDirection:'row',gap:10}}><Icon name="shield" size={18} color={colors.goldDark}/><Text style={{...type.bodySmall,color:colors.text,flex:1}}>Verify the address carefully. Confirmed RainX transactions cannot be reversed.</Text></View><Button title="Review & send" onPress={send} loading={busy} disabled={!parsed||!/^/.test(to.trim())}/></View></Animated.View></Screen>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View><Text style={{...type.caption,color:colors.muted,marginBottom:7}}>{label.toUpperCase()}</Text><View style={{backgroundColor:colors.card,borderWidth:1,borderColor:colors.hairline,borderRadius:radius.md,paddingHorizontal:14,paddingVertical:4}}>{children}</View></View>}
const styles={input:{fontSize:17,color:colors.text,minHeight:50},amount:{fontSize:32,fontWeight:'700' as const,color:colors.text,minHeight:58}};
