import React, { useState } from 'react';
import { Alert, Linking, Text, TextInput, View } from 'react-native';
import { useApp } from '../store/app';
import { clearWallet } from '../store/wallet';
import { Screen } from '../components/Screen';
import { SectionHeader } from '../components/SectionHeader';
import { Button } from '../components/Button';
import { colors, radius } from '../theme/colors';
import { type } from '../theme/typography';
import { Icon } from '../components/Icons';
export function Settings({navigation}:any){const{wallet,rpcUrl,setRpcUrl,reloadWallet}=useApp();const[next,setNext]=useState(rpcUrl);const save=()=>{setRpcUrl(next.trim().replace(/\/$/,''));Alert.alert('Network updated','The wallet will now read from the new RainX node URL.');};return <Screen><Text style={{...type.title,color:colors.text}}>Settings</Text><Text style={{...type.bodySmall,color:colors.muted,marginTop:5}}>Security, wallet and network controls.</Text><View style={{marginTop:24}}><SectionHeader title="Wallet"/><Row icon="shield" title="Recovery phrase" subtitle="View your offline backup" onPress={()=>navigation.navigate('BackupPhrase')}/><Row icon="copy" title="Address" subtitle={wallet?.address||'—'} onPress={()=>{}}/></View><View style={{marginTop:26}}><SectionHeader title="Network"/><View style={{backgroundColor:colors.card,borderWidth:1,borderColor:colors.hairline,borderRadius:radius.lg,padding:16}}><Text style={{...type.caption,color:colors.muted}}>RAINX RPC URL</Text><TextInput value={next} onChangeText={setNext} autoCapitalize="none" autoCorrect={false} style={{fontSize:16,color:colors.text,marginTop:8,minHeight:46}}/><Button title="Save node" onPress={save}/><Text style={{...type.caption,color:colors.muted,marginTop:10}}>For a phone on the same LAN as your node, use the node computer's local IP, e.g. http://192.168.1.20:27778.</Text></View></View><View style={{marginTop:26}}><SectionHeader title="About"/><Row icon="network" title="RainX Chain" subtitle="Independent native blockchain • Protocol v1"/><Row icon="activity" title="Source" subtitle="Open source protocol + mobile client"/></View><View style={{marginTop:28}}><Button title="Remove wallet from this device" variant="danger" onPress={()=>Alert.alert('Remove wallet?','Make sure your recovery phrase is safely backed up.',[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{await clearWallet();await reloadWallet();}}])}/></View></Screen>}
function Row({icon,title,subtitle,onPress}:{icon:string;title:string;subtitle:string;onPress?:()=>void}){const{Pressable}=require('react-native');return <Pressable onPress={onPress} style={{minHeight:65,backgroundColor:colors.card,borderWidth:1,borderColor:colors.hairline,borderRadius:radius.md,padding:13,flexDirection:'row',alignItems:'center',marginBottom:8}}><View style={{width:38,height:38,borderRadius:12,backgroundColor:colors.goldSoft,alignItems:'center',justifyContent:'center'}}><Icon name={icon} size={18} color={colors.goldDark}/></View><View style={{flex:1,marginLeft:12}}><Text style={{...type.body,color:colors.text,fontWeight:'700'}}>{title}</Text><Text numberOfLines={1} style={{...type.caption,color:colors.muted,marginTop:2}}>{subtitle}</Text></View><Icon name="chevron" size={18} color={colors.muted}/></Pressable>}
